### ISSUE TITLE
Verify artifacts using the trust store and trust policy

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#102]
Notation will have [new CLI commands to manage trust policy](https://github.com/notaryproject/notation/pull/568/files) in Notation v1.0.0-RC.4, which allows users to initialize trust policies with default values, import trust policies from a JSON file, and show trust policies. We hope there is a guide to tell users about its usage and samples when using this `notation policy command` in signature verification process.

**Comment by FeynmanZhou** [comment]
We have added the first guide for this scenario: https://notaryproject.dev/docs/tutorials/trust-policy/. Will continue on this item in RC.3 with Trust Policy CLI.

**Comment by zr-msft** [comment]
@FeynmanZhou my understanding is that you want an additional guide written with the additions in RC3 of the Trust Policy CLI. Do the early builds of RC3 have enough functionality for me to start writing, or is it blocked?

**Comment by zr-msft** [comment]
Labeling as blocked until details are provided

**Comment by FeynmanZhou** [comment]
Hi @zr-msft ,

Sorry for missing details in this issue. As Notation will have [new CLI commands to manage trust policy](https://github.com/notaryproject/notation/pull/568/files) in Notation v1.0.0-RC.4, we hope there is a guide to tell users about its usage and samples.

**Comment by zr-msft** [comment]
@FeynmanZhou thank you for the context.  Based on reviewing the information in this issue again, docs progress is still blocked until I have some build of the CLI with working functionality that I can test and use to build out the doc. Please update this issue and removed the blocked tag once there is a CLI build available with this functionality.

**Comment by FeynmanZhou** [comment]
This issue is created for v1.0.0-RC.4 which will be released at the end of Mar. We will remove the blocked tag once the Notation v1.0.0-RC.4 is ready to be tested. We will have a dev build release before the official release. I will let you know when the dev build release is out. Thanks!

**Comment by yizha1** [comment]
Closed as we have one tutorial ready https://notaryproject.dev/docs/tutorials/trust-policy/
