### ISSUE TITLE
Delete and clean up test key and self-signed cert file

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#103]
Users can use `notation cert generate-test` to generate the test key and self-signed certificate locally for testing purposes. However, Notation doesn't support deleting the test key and certificate file from the local file system using `notation key delete` and `notation cert delete`. See related issue https://github.com/notaryproject/notation/issues/604 and PR https://github.com/notaryproject/notation/pull/606.

We need to create a guide to tell users how can they clean up the test key and certificate file effectively. Otherwise, users will not be able to re-generate the test key/cert using the same name although the key/cert has been removed.

```
# Generate the test key and self-signed cert, and set the test key as the default signing key
$ notation cert generate-test --default "wabbit-networks.io"

# Remove the specified key from the signing key list
$ Notation key delete wabbit-networks.cn
wabbit-networks.cn: unmarked as default // the output will be improved in RC.4

# Get the test key and cert path
$ notation key ls

# Delete the specified key from the local file system
$ rm /home/azureuser/.config/notation/localkeys/wabbit-networks.cn.key

# Delete the corresponding cert from the Trust Store
$ notation cert delete  --type ca --store wabbit-networks.cn wabbit-networks.cn.crt
Are you sure you want to delete "wabbit-networks.cn.crt" in "wabbit-networks.cn" of type "ca"? [y/N] y
Successfully deleted /home/azureuser/.config/notation/truststore/x509/ca/wabbit-networks.cn/wabbit-networks.cn.crt

# Delete the corresponding cert from the local file system
$ rm /home/azureuser/.config/notation/localkeys/wabbit-networks.cn.crt
```

**Comment by zr-msft** [comment]
@FeynmanZhou I don't understand what the docs request is here. Can you provide more context and details for what you're looking for?

**Comment by FeynmanZhou** [comment]
@zr-msft Sorry for missing the context in this issue. I just renamed the issue and provided the more detailed context in the description. Is it helpful?

**Comment by zr-msft** [comment]
Thank you @FeynmanZhou, updates are exactly what i needed. See linked PR with my doc.
