### ISSUE TITLE
Verify Notation signature before deploying the signed image to Kubernetes cluster

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#107]
After signing an image with Notation, how can users verify the image integrity and signature before deploying this image to Kubernetes cluster? The solutions like [Ratify](http://ratify.sh/) and [Kyverno](https://github.com/kyverno/website/issues/804) have integrated and supported verifying Notation signatures. We need to tell users how can they find the right guideline resources on the Notary website.

**Comment by FeynmanZhou** [comment]
Sorry for the late response. For this issue, I realized the related doc has been added to the Ratify website and will be added to the Kyverno website soon. So we may just need to provide related doc links and elaborate on the validation scenarios in Kubernetes on the Notary website.

**Comment by FeynmanZhou** [comment]
Now there are two related guides published on the Ratify and Kyverno website:
- Ratify: [Sign and verify an image with Notation, Ratify, and OPA Gatekeeper | Ratify](https://ratify.dev/blog/sign-and-verify-image-with-notation-ratify/) and Kyverno website.
- Kyverno: [Using Notary with Kyverno](https://kyverno.io/docs/writing-policies/verify-images/notary/) 

We need to create a new page on the Notary Project documentation to elaborate on the verification scenario in Kubernetes and add links to those two guides.

**Comment by Roseline-Bassey** [comment]
@FeynmanZhou, could you assign me this issue?

**Comment by yizha1** [comment]
Remove the milestone since Notation v1.0.0 was released.
