### ISSUE TITLE
Project twitter account

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#11]
Is there a twitter account for Notary Project? If there is, we can add it to the footer, and to the [community](https://notaryproject.dev/community/) page.

**Comment by toddysm** [comment]
CC:// @bridgetkromhout ^^

**Comment by karenhchu** [comment]
I'll need an email account to register with. Is there mailing list all the the maintainers are on so that there's shared access if/when people leave?

**Comment by toddysm** [comment]
I don't think so - we will need to also create mailing lists for maintainers and community - see #12

**Comment by karenhchu** [comment]
I believe the maintainer mailing list is something that needs to be coordinated with CNCF. I'd imagine there's already an existing one since it's usually pulled from the maintainer list file in the project repo. I'd recommend starting with the CNCF Service Desk.

**Comment by toddysm** [comment]
@FeynmanZhou would you mind checking with CNCF and updating the issue with details?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou would you mind checking with CNCF and updating the issue with details?

Yes. I will confirm the Notary email with CNCF. After we get the email, we can register a Twitter handle.

**Comment by FeynmanZhou** [comment]
@toddysm @nate-double-u @karenhchu I registered a Twitter handle for Notary: https://twitter.com/NotaryProject.
I will close this issue as we completed it.
