### ISSUE TITLE
Creating a "legit" CA-SubCA-SigningCert for Notary

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notaryproject.dev#111]
After some discussion with @dtzar, I'll post this issue here so we can decide how to handle forward. Posing in his own words.

I decided that it isn't worth following the path to try and get a code signing certificate from a 3rd party CA (i.e. using [this link for Azure Key Vault integration](https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-integrate-certificate-authority)) may be unwelcome because:

- That would only get you a signing certificate (although super legit! since it has a proper 3rd-party well known CA)
- It would be cost prohibitive - based on pricing on their public page for any certs didn't try to pull the trigger to buy one,
- If that one cert went bad/hacked or wanted to break this out into different departments, etc, then you'd have to pay for an entire new one every time
- Can't just trust a root CA since the root CA could be issuing certs for other people doing signing and you don't want to trust those

What we really need is guidance to create a CA, sub-CA, then issue appropriate certificate for use with Notary signing.  Ideally this would use all OSS or could be automated to a good extent. 
 
While I expect enterprises to have the CA/Sub-CA setup already baked long ago, I still see value in even a "small shop" and others who want to go deeper to utilize or understand the process and be able to do it on their own. It would also help enterprises with a proper CA setup to more easily create the certificate(s) they need.
 
My gut is to figure out how to do this with openssl (i.e. see [Create your own Certificate Authority (CA) using OpenSSL - arminreiter.com](https://arminreiter.com/2022/01/create-your-own-certificate-authority-ca-using-openssl/?msclkid=e581d253c81b11ec8bcaf89da5296ed1) and [Openssl: Setup an intermediate CA (michlstechblog.info)](https://michlstechblog.info/blog/openssl-setup-an-intermediate-ca/?msclkid=0dd94a5ec81c11ec9862969858389eb2)).

However, I'd like to hear perspectives from others as there are many options in this space.

For now we have details on the [signing requirements](https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#signature-algorithm-requirements) and IMO a [too basic and no-explanation example ](https://github.com/Azure/notation-azure-kv/blob/main/docs/nv2-sign-verify-aks.md#store-the-signing-certificate-in-azure-key-vault)in our docs which just uses this to create a self-issued signing cert:

```
cat <<EOF > ./my_policy.json
{
    "issuerParameters": {
    "certificateTransparency": null,
    "name": "Self"
    },
    "x509CertificateProperties": {
    "ekus": [
        "1.3.6.1.5.5.7.3.1",
        "1.3.6.1.5.5.7.3.2",
        "1.3.6.1.5.5.7.3.3"
    ],
    "subject": "CN=${KEY_SUBJECT_NAME}",
    "validityInMonths": 12
    }
}
EOF
```

**Comment by zr-msft** [comment]
@toddysm @FeynmanZhou Is this intended to be the start of a discussion? If not, what is the specific docs request here?

I see a mention of docs, but no specific call to action
> For now we have details on the [signing requirements](https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#signature-algorithm-requirements) and IMO a [too basic and no-explanation example ](https://github.com/Azure/notation-azure-kv/blob/main/docs/nv2-sign-verify-aks.md#store-the-signing-certificate-in-azure-key-vault)in our docs which just uses this to create a self-issued signing cert:


- Are you asking to for a doc showing CA/sub-CA/cert creation using OSS with `notation` then using that cert to sign and verify?
- Are you planning on adding something to `notation` related to this?

**Comment by FeynmanZhou** [comment]
Removed the p1 label as it is an open question for the community. We need to investigate the scenarios first before writing the doc.

**Comment by yizha1** [comment]
Need further discussion, so update the milestone accordingly

**Comment by yizha1** [comment]
Reopen it as it is still a valid ask, and put it under `future` milestone
