### ISSUE TITLE
Document how Notation handles the credential storage in an environment where Docker is installed

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#116]
@priteshbandi has a question regarding how Notation handles the credential storage in an environment where Docker is installed. For example, do we need Docker client running on the machine for registry creds in Notation? 

There might have different cases in different OS. We need to document it on the website.

**Comment by priteshbandi** [comment]
Doc reference: https://github.com/docker/docker-credential-helpers#available-programs

**Comment by zr-msft** [comment]
@FeynmanZhou have you all made decisions about how `notation` implements this? If so can you provide the details here. Otherwise issue is blocked

**Comment by FeynmanZhou** [comment]
@zr-msft Yes. Currently, Notation requires Docker as a prerequisite and Notation will read the registry credential configuration from `~/.docker/config.json`. It requires users to configure the [Docker Credential Store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) in a VM. This dependency will be removed in the Notation v1.0.0 release (tentatively in the mid of Apr) and configuration will be simplified. Before v1.0.0, we need to prepare a guide to tell users about this configuration.

**Comment by FeynmanZhou** [comment]
@zr-msft This typically happens in the Linux environment. We have several users who encountered this problem.
BTW, there is an introduction at https://github.com/notaryproject/notation/blob/main/specs/registry-auth.md#credential-store.

**Comment by FeynmanZhou** [comment]
I agree there is no need to invest more time writing this guide. We can tell users to specify flags `--username` / `--password` or environment variables `NOTATION_USERNAME` / `NOTATION_PASSWORD` to bypass this problem before v1.0.0.

**Comment by zr-msft** [comment]
@FeynmanZhou per these comments:
- https://github.com/notaryproject/notaryproject.dev/pull/149#pullrequestreview-1360103112
- https://github.com/notaryproject/notaryproject.dev/pull/149#discussion_r1149552866

it seems like the ENV VAR approach is currently not working, do you plan to fix this before 1.0? 

Also, based on the discussion, it seems like the issue should be close. If so, can you close it?
