### ISSUE TITLE
Notary Project email list

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#12]
Is there a Notary Project maintainers/developers email list or google group? If so, we can add it to the [community page](https://notaryproject.dev/community/)

**Comment by FeynmanZhou** [comment]
Not yet. We can register a new one if this is required or recommended by CNCF. Currently we are using GitHub Discussion.

**Comment by toddysm** [comment]
@karenhchu and @bridgetkromhout is this something that you can help with?

**Comment by nate-double-u** [comment]
If the project wants an email list (if there isn't one already), I can create one using https://lists.cncf.io/

**Comment by nate-double-u** [comment]
It seems like there _is_ an internal maintainers list -- but i don't recommend publishing that one. If the project wants a second, public facing, email list let me know -- if not, that's fine, we can close this issue 🙂

**Comment by toddysm** [comment]
We may need three different lists:
- Maintainers (this can be the internal one that you mentioned) - this doesn't need to be published on the site
- Security one (can be the same people as above but with security@notaryproject.dev email address) used to report security issues - this should be published on the site
- General mailing list for discussions - this should be published on the site

**Comment by zr-msft** [comment]
@nate-double-u and @toddysm have these lists already been created and can i close this issue?

**Comment by nate-double-u** [comment]
> @nate-double-u and @toddysm have these lists already been created and can i close this issue?

I think so.
