### ISSUE TITLE
Document how to retrieve the descriptor of an artifact

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#120]
We need to provide a guideline to tell users how to retrieve the descriptor of an artifact that is sent for signing. 

To retrieve the descriptor of an artifact from the remote registry, we can use `oras manifest fetch --descriptor`.

To retrieve the descriptor of a signature:
- COSE signatures: any CBOR inspector will help on reading the payload
- JWS signatures: to base64 decode the payload field of the JSON object

It should be documented on the website for troubleshooting purposes.

**Comment by FeynmanZhou** [comment]
> To retrieve the descriptor of a signature:
> - COSE signatures: any CBOR inspector will help on reading the payload
> - JWS signatures: to base64 decode the payload field of the JSON object

@shizhMSFT Could you pls help to recommend the 3p tools that we can leverage to handle the two requirements above?

**Comment by shizhMSFT** [comment]
@FeynmanZhou Shouldn't the customer use `notation inspect` to retrieve the signed descriptor?

**Comment by FeynmanZhou** [comment]
@shizhMSFT Yes. [notation inspect](https://github.com/notaryproject/notation/blob/main/specs/commandline/inspect.md) can obtain the descriptor of a signature. 

The scenario is to troubleshoot issues with signatures. This is what `notation inspect` is supposed to do. If a user is troubleshooting a signature, she/he should be able to extract what is the signed content and compare it with the content that is expected to be signed.
