### ISSUE TITLE
Website: Make the “News & Blogs” section to be dynamic

### ISSUE THREAD

**Issue by thisisobate** [notaryproject/notaryproject.dev#128]
Follow-up from #110

**Comment by FeynmanZhou** [comment]
@thisisobate Hi, would you be able to continue work on this item? Currently, we need to manually update the index.html file to update new blogs on the landing page.

**Comment by thisisobate** [comment]
@FeynmanZhou Sure, will pick up this item as soon as I round up with my current task.

**Comment by nate-double-u** [comment]
@FeynmanZhou, is this a high priority? I'd like to suggest that this work be done by community members, or potentially if we can put some more website issues together, this could be done as a part of a mentorship -- maybe [term 2](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/02-Jun-Aug), or [term 3](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/03-Sep-Nov)?

**Comment by FeynmanZhou** [comment]
@nate-double-u @thisisobate 
Yes. only this issue is a left-over work for the landing page and is a high priority. It will make the blogger's life much easier and no long to manually maintain this section : ) 

Other work items & issues could be added to the LFX program term 2. Thank you!

**Comment by Amishakumari544** [comment]
Hello everyone, I am willing to work on this but I am a beginner here and need some references or guidance on how to implement this feature.

**Comment by FeynmanZhou** [comment]
@Amishakumari544 Thank you for your help! The current problem is that we need to manually update the [blog section](https://github.com/notaryproject/notaryproject.dev/blob/main/content/en/_index.html#L287) in the landing page. It should read the content list from the blog page. Our expectation is to enable automatic updates to the blog section when a new blog is added.

You can also contact @thisisobate for guidance.

**Comment by hamees-sayed** [comment]
hi @FeynmanZhou I'd like to to work on this issue

**Comment by kayceeDev** [comment]
@thisisobate @FeynmanZhou  Can I take up this issue?

**Comment by 1Shubham7** [comment]
hi @FeynmanZhou can I take this issue ?
