### ISSUE TITLE
Create a demo video for the new landing page

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#129]
We are working on the new Notary website with CNCF. Now we are looking for a technologist who can help us record a demo video for Notation, which will be used on the new landing page ([preview link](https://deploy-preview-110--notarydev.netlify.app/)). 

Considering Notation is a CLI tool, our target is to catch people's eye on their first look and let them understand what is Notation, when, and how to use it in 3~5 minutes.

**Comment by jlbutler** [comment]
I'd be happy to work on this @FeynmanZhou , we can talk about it in an upcoming community call.

**Comment by FeynmanZhou** [comment]
Per the discussion with @jlbutler , we will have the first version at the end of Feb. Thanks.

**Comment by jlbutler** [comment]
This can be assigned to my colleague @svennam92 thank you @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Thank you @jlbutler and @svennam92👍 

Hi @svennam92, I would appreciate it if you could comment on this issue then we will be able to assign it to you.

**Comment by svennam92** [comment]
Hey @FeynmanZhou — I've discussed with Jesse and I'm excited to work on a lightboard demo video for Notation. Planning to have something to review next week.

**Comment by FeynmanZhou** [comment]
> Hey @FeynmanZhou — I've discussed with @jlbutler and I'm excited to work on a lightboard demo video for Notation. Planning to have something to review next week.

Awesome! @svennam92 Shall we have a short meeting to discuss the idea?

**Comment by svennam92** [comment]
@FeynmanZhou Let's do it, I've sent you a DM in the Kubernetes public Slack.
