### ISSUE TITLE
Create a blog post for Notary fuzzing test and include fuzzing report

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#142]
Notary has started the fuzzing test on [oss-fuzz](https://github.com/google/oss-fuzz/tree/master/projects/notary) recently and fixed 4 critical fuzzing issues. [AdamKorcz](https://github.com/AdamKorcz) suggests the Notary team create a blog post for the Notary fuzzing test. We will collaborate with Adam to create and publish this blog post at http://notaryproject.dev/

**Comment by yizha1** [comment]
Close issue as PR https://github.com/notaryproject/notaryproject.dev/pull/152 was merged
