### ISSUE TITLE
Notation login returns unfriendly error

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notaryproject.dev#156]
Related to the following comment on the documentation https://github.com/notaryproject/notaryproject.dev/pull/149#discussion_r1146957012 trying to sign into Docker Hub I get the following error:

```
~> notation login docker.io                                                                              
Error: failed to store credentials: error storing credentials - err: no credentials username, out: `no credentials username`
```

We need to fix the error message and provide consistent experience with other tools to prompt for the username and password instead.

**Comment by toddysm** [comment]
I am fine closing this one in this repo but I would like to make sure that https://github.com/notaryproject/notation/issues/503 and https://github.com/notaryproject/notation/pull/566 implement better error messages.

**Comment by yizha1** [comment]
@toddysm Is it OK to close this issue, since https://github.com/notaryproject/notation/issues/503 and https://github.com/notaryproject/notation/issues/503 were closed.

**Comment by zr-msft** [comment]
@toddysm @yizha1 closing this issue
