### ISSUE TITLE
Need to work on README File

### ISSUE THREAD

**Issue by carrycooldude** [notaryproject/notaryproject.dev#157]
- Not proper documentation 
- As a beginner, I don't know what this project is about and how to start using the local system

**Comment by FeynmanZhou** [comment]
Thanks. Have you checked the doc on the website? https://notaryproject.dev/docs/quickstart/

**Comment by carrycooldude** [comment]
> Thanks. Have you checked the doc on the website? https://notaryproject.dev/docs/quickstart/

Yes but many beginners like me 
Will not see much in the content/doc folder 
It's better to have some more content at Main ReadMe file

**Comment by carrycooldude** [comment]
> > > Thanks. Have you checked the doc on the website? https://notaryproject.dev/docs/quickstart/
> > 
> > Yes but many beginners like me Will not see much in the content/doc folder It's better to have some more content at Main ReadMe file
> 
> Do you expect to add the quick start content to the README in this website repo instead of the [Notation CLI repo](https://github.com/notaryproject/notation)? 

Yes!!!
