### ISSUE TITLE
Update installation guide on macOS and Windows to RC.3

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#159]
@zr-msft I just noticed the installation guide on macOS and Windows still points to RC.2 as the latest release. Would you mind opening a follow-up PR to update them to RC.3? Thanks

_Originally posted by @FeynmanZhou in https://github.com/notaryproject/notaryproject.dev/pull/144#discussion_r1147814730_

**Comment by zr-msft** [comment]
Good catch @FeynmanZhou ! See linked PR with fix
