### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#16]
Currently the landing page is a stub.

Bring content in from https://github.com/notaryproject/notaryproject/blob/main/README.md

Look at [etcd.io](https://etcd.io) and [grpc.io](https://grpc.io) as examples for content and layout.

Questions:
* Does Notary Project have a preferred one-liner description we can use under the logo in the hero section?
* "What is Notary Project?" or "Why Notary Project?"
  * Currently this has placeholder copy from the README file -- is this appropriate?
* Which 2-4 features should we highlight?
  * Which format is prefered -- etcd or grpc (both can be used fairly easily, tho etcd works best with 4 features)
* Used by section - who is using Notary? (V1 or V2?)
* Footer
  * Copyright date range currently set to "© 2013-2021 Notary Project Authors" -- what is the correct date range? (https://github.com/notaryproject/notaryproject.dev/pull/64)
  * We can add a couple more icons, [twitter](https://github.com/notaryproject/notaryproject.dev/issues/11), and [google groups/email list](https://github.com/notaryproject/notaryproject.dev/issues/12)

**Comment by nate-double-u** [comment]
Based on a conversation with @SteveLasker, @bridgetkromhout, and @AevaOnline, the front page should be reorganized around the idea that the Notary Project is the host to three projects, rather than showing just a notary logo and snippets explaining it, I think we should revise to show all three projects/logos, with snippets, which would link to the individual project landing pages.

```
Header: Top level nav
```

```
(Jumbotron)
TUF | Notary | Notation
```

```
About Notary Project
```

```
Footer
```

More detail about how to organize the info can be found in [Information Architecture Proposal #23](https://github.com/notaryproject/notaryproject.dev/issues/23)

**Comment by nate-double-u** [comment]
Even if we don't get the layout changed, we should at least update the blurb as it is no longer representative of the whole Notary Project.

**Comment by yizha1** [comment]
updated milestone to `discussion` since it is not mandatory for rc.1

**Comment by zr-msft** [comment]
@toddysm @yizha1 @nate-double-u 

This page like it has been updated:
https://notaryproject.dev//

Can we close this issue?

**Comment by FeynmanZhou** [comment]
@zr-msft I think we can close it as we launched the new landing page last week. Just closed it. 
cc @toddysm @yizha1 @nate-double-u @iamsamirzon @vaninrao10
