### ISSUE TITLE
Create a chapter for CLI reference doc

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#163]
We can generate the CLI reference doc for Notation CLI using [Cobra](https://umarcor.github.io/cobra/#documentation-generation). I think we can add the CLI reference doc to the Notary documentation, which is similar to https://oras.land/cli_reference/. It will provide fundamental references for users based on the CLI help information.

**Comment by FeynmanZhou** [comment]
Yeah. Thanks for the advice. I think it's doable. 
We can add the first version of CLI reference docs by following the steps above. 
I can also share the steps on how to generate the CLI reference doc based on the Notation CLI repo here.

**Comment by zr-msft** [comment]
@FeynmanZhou any updates on generating/sharing the initial CLI reference docs?

**Comment by FeynmanZhou** [comment]
Sorry for the late response. I generated the initial CLI reference docs using Cobra. You can download it from [notation-reference-doc.zip](https://github.com/notaryproject/notaryproject.dev/files/11320512/notation-reference-doc.zip).

Here are the steps to generate the CLI reference doc:

1. Clone the Notation CLI repo: https://github.com/notaryproject/notation.git

2. Modify the [main.go](https://github.com/notaryproject/notation/blob/main/cmd/notation/main.go) as follows:

```
package main

import (
	"os"

	"github.com/notaryproject/notation/cmd/notation/cert"
	"github.com/notaryproject/notation/cmd/notation/policy"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc" // Add this line to import cobra doc lib
)

func main() {
	cmd := &cobra.Command{
		Use:          "notation",
		Short:        "Notation - a tool to sign and verify artifacts",
		SilenceUsage: true,
	}
	cmd.AddCommand(
		signCommand(nil),
		verifyCommand(nil),
		listCommand(nil),
		cert.Cmd(),
		policy.Cmd(),
		keyCommand(),
		pluginCommand(),
		loginCommand(nil),
		logoutCommand(nil),
		versionCommand(),
		inspectCommand(nil),
	)
	if err := doc.GenMarkdownTree(cmd, "/notation-reference-doc"); err != nil {    
		os.Exit(1)
	}
}
```
3. Create a folder `notation-reference-doc` that we defined in `main.go` to store the initial CLI reference docs generated by Cobra. 

4. Make sure Golang v1.20.x is installed locally. Then you can run this project in VS Code as follows.

![image](https://user-images.githubusercontent.com/40452856/234225446-1fe2b0dc-176b-412b-b0fb-a906a4b517ac.png)
