### ISSUE TITLE
Create tutorial for certificate revocation

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#165]
Certificate revocation is the new feature for RC-4. A tutorial guide is needed for users to understand usage of this feature. This guide will be placed under https://github.com/notaryproject/notaryproject.dev/tree/main/content/en/docs/tutorials

**Comment by kody-kimberl** [comment]
Commenting to allow assignment

**Comment by zr-msft** [comment]
Labeling as blocked until RC4 ships

@yizha1 do you see this as something that needs a full end-to-end scenario to show how it works? Or does it just need a feature guide to show how the feature works with some example commands?

**Comment by kody-kimberl** [comment]
> Labeling as blocked until RC4 ships
> 
> @yizha1 do you see this as something that needs a full end-to-end scenario to show how it works? Or does it just need a feature guide to show how the feature works with some example commands?

I don't think we can provide an end-to-end scenario for this, as getting different revocation results would require having a mock server set up to intercept the requests. Additionally, I'm not really sure if the user would need example commands, as performing the revocation check is entirely dependent on the trust policy. IMO I think just documenting what the potential results are and how to ensure the trustpolicy is set up properly to include a revocation check is the most important part.
