### ISSUE TITLE
Create tutorials for experimental feature sign/verify images in oci image layout directory

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#166]
`sign/verify images in OCI image layout directory` is the new experimental feature for RC-4. A tutorial guide is needed for users to understand usage of this feature. This guide will be placed under https://github.com/notaryproject/notaryproject.dev/tree/main/content/en/docs/tutorials

**Comment by zr-msft** [comment]
Since this is an experimental feature, i think it should be low priority.

Also, labeling as blocked until RC-4 ships

**Comment by yizha1** [comment]
@zr-msft here is a guide FYI

https://hackmd.io/8MLW8iQCTI-WNwvYb9Vykw
