### ISSUE TITLE
Reducing the PR approval count from 3 to 2

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#169]
To increase the velocity of the website and documentation development, we would like to reduce the PR approval count to 2. The justification is the following: with the current count of 3 approvals we have 4 people who need to be involved in the PR. Our initial goal was to have min 3. By reducing to 2 approvals required we still have 3 people including the original submitter. 

Considering this is a website repository, there are always some small wording fixes or tiny layout updates on the content that we hope to reflect on the website immediately. It helps the PR authors get the updates effectively and enables users to consume the latest content.

**Comment by yizha1** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by yizha1** [comment]
We reached consensus with most `notaryproject.dev` maintainers (4/6 people). The next step is to enforce the new policy in `notaryproject.dev`  repo.

**Comment by FeynmanZhou** [comment]
Thank you all. I have updated the branch policy in this repo accordingly: 
![image](https://user-images.githubusercontent.com/40452856/231650954-da50733c-b04d-4177-8142-273f2735456f.png)
