### ISSUE TITLE
Refactor Concepts section

### ISSUE THREAD

**Issue by zr-msft** [notaryproject/notaryproject.dev#172]
Per feedback from @FeynmanZhou 

remove duplicate content from concepts section that already exist in https://github.com/notaryproject/notaryproject/tree/main/specs

**Comment by FeynmanZhou** [comment]
@zr-msft Thanks. My thought is to refactor the Concepts chapter to Glossary, to help users better understand those terms and definitions in the context of the Notary project. Istio and Kubernetes documentation has a similar chapter:

https://istio.io/latest/docs/concepts/observability/
https://kubernetes.io/docs/reference/glossary/

I saw #173 removed those files. Will you help to prepare new content for the Concepts chapter from scratch? I think we can extract the appropriate content from the [Spec](https://github.com/notaryproject/notaryproject/tree/main/specs) and rephrase it from end-users perspective.

**Comment by zr-msft** [comment]
@FeynmanZhou i will help rebuild out the concepts section from scratch, but we'll need to scope the work and identify the concepts you want to cover. I also think that needs to be handled in its own issues and PRs. Lets keep this focused removing all the duplicate content and get the PR merged.

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou i will help rebuild out the concepts section from scratch, but we'll need to scope the work and identify the concepts you want to cover. I also think that needs to be handled in its own issues and PRs. Lets keep this focused removing all the duplicate content and get the PR merged.

Make sense.

**Comment by FeynmanZhou** [comment]
@zr-msft There is a good [reference](https://github.com/notaryproject/notaryproject/blob/main/requirements/definitions-terms.md) for preparing the new Concepts chapter.
