### ISSUE TITLE
Create a blog post for Notation v1.0.0

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#191]
Notation v1.0.0 will be available in the middle of May. We need to create a blog post for Notation v1.0.0 to summarize the updates.

**Comment by 1Shubham7** [comment]
@FeynmanZhou I think I can get this issue done. Please assign it to me

**Comment by FeynmanZhou** [comment]
@1Shubham7 Thanks for your interest. This issue is for Notary maintainers. We can also add you as the reviewer for the blog.
