### ISSUE TITLE
Add float copy button for the command lines

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#193]
It is not convenient to copy command lines especially for long command lines, for example, here is a screenshot for [notation quick start](https://notaryproject.dev/docs/quickstart/), you need to scroll the right most to copy the whole command.

![image](https://user-images.githubusercontent.com/107919912/237034005-ff97ccbd-3995-40cf-b4bb-dfa9818fe0e3.png)

Suggest adding a float copy button for users to copy the command lines easily.

**Comment by Sumitmaithani** [comment]
👋 Hey @yizha1! can I work on this issue? 🔧😎

**Comment by FeynmanZhou** [comment]
@Sumitmaithani You are welcome to work on that.

**Comment by Sumitmaithani** [comment]
After some investigation, I discovered that the Hugo Doscy template does not have a built-in option for a copy button. This feature is available in the PaperMod template by setting "ShowCodeCopyButtons: true" in a content file that has a code block. However, to implement this feature in Doscy, we may need to write custom logic.
