### ISSUE TITLE
Develop content for Notary documentation and blogs

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#195]
This issue relates to a proposal for a [LFX mentorship project](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug) for Term 2, 2023.  Please feel free to comment on this issue about your interest and willingness, but note that commenting here is not the same as applying to LFX.

- Description: Develop content for Notary documentation and write blog posts to educate users about the Notary use cases. Write user guides, contributing guides, and developer guides for every new Notary release and keep those content up-to-date.
- Expected Outcome: 
   - Write user guides with end-to-end scenarios based on given doc structure and requirement
   - Write contributing guides and developer guides, ensure new developers can easily build and start contributing to Notary subprojects 
   - Write blog posts to educate users to use Notation with cloud-native ecosystem tools
- Recommended Skills: OCI, Docker, Kubernetes, Notary, Git, Markdown, Technical writing experience
- Mentor(s): Mentor(s):  Yi Zha, @yizha1 (yizha1@microsoft.com)

**Comment by Adi9235** [comment]
Hi @FeynmanZhou I am also interested to work on this project

**Comment by 1Shubham7** [comment]
can I work on this isuue?

**Comment by AayushSaini101** [comment]
@FeynmanZhou I am Interested in this project. I have already shared all the required details in the Portal. 
Thanks 
[Aayush ](https://www.linkedin.com/in/aayush-saini-0a25931b1/ )

**Comment by Roseline-Bassey** [comment]
Hey @FeynmanZhou, I am writing to express my interest in this project.

**Comment by deveshgoyal1000** [comment]
Hey 👋@FeynmanZhou iam interested to work on this project with zeal.

**Comment by Vikash-8090-Yadav** [comment]
Hey @FeynmanZhou I am very much interested in this project. The skill u have mentioned totally align with my expertise. 
Thank You!.

**Comment by harshsingh32** [comment]
I would like to work on this issue but I have applied to three mentorship program couldn't apply to this issue. But I would like to work on this issue apart from lfx mentorship. I would like to improve the documentation of this project making it engaging for the users and make it more expressive. A good documentation increase the engagement of users with the project and motivate them to contribute to the community and project.

**Comment by harshsingh32** [comment]
I made a issue under this #242.
