### ISSUE TITLE
Text is overflowing outside of the navigation bar in the mobile version

### ISSUE THREAD

**Issue by lata-11** [notaryproject/notaryproject.dev#199]
In the mobile version of the homepage, the text in the upper navigation bar is overflowing, which is causing readability issues as well as a less appealing user interface.
![image](https://github.com/notaryproject/notaryproject.dev/assets/103296906/c13dc19d-c353-4671-a985-f98edf2f4188)
![image](https://github.com/notaryproject/notaryproject.dev/assets/103296906/a6d1e00b-6e51-4b45-9fb4-dd3897acc818)

**Comment by lata-11** [comment]
Hey! I have noticed this issue on the Notary website. I would like to solve this issue. Can I work on it?

**Comment by FeynmanZhou** [comment]
Thanks for reporting this issue and showing your interest. The mobile adaptive experience is still in WIP and can be improved a lot. I see #205 and #206 are opened to fixing this issue. Would you mind helping us review them? We will only accept and merge one PR into `main`.

**Comment by krishnasvp** [comment]
Can I please take this up?

**Comment by lata-11** [comment]
Hey! There already two PR #205 and #206 have been raised for this issue. So, I wouldn't recommend you work on this issue. Thanks.

**Comment by PranitPatil03** [comment]
hello @lata-11 

I have made changes to the images in the PR. Would you kindly review these updates?

Thank you

**Comment by lata-11** [comment]
Thanks, @PranitPatil03! I would be happy to help.
