### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by BabyElias** [notaryproject/notaryproject.dev#208]
![image](https://github.com/notaryproject/notaryproject.dev/assets/95405559/b72de164-fe03-4832-979b-b18bba63b701)
The link relating How to contribute is broken.
![image](https://github.com/notaryproject/notaryproject.dev/assets/95405559/9c45d704-fe85-4f87-8abd-854a02bde992)

**Comment by PranitPatil03** [comment]
Hello @BabyElias 👋

I can work on this issue. The simplest solution would be to provide an accurate hyperlink for the contributing section.

**Comment by BabyElias** [comment]
Hey @PranitPatil03 , I am a contributor myself. And want to work on this. Thank you so much for your interest!
