### ISSUE TITLE
Size Inconsistency in Mobile View

### ISSUE THREAD

**Issue by BabyElias** [notaryproject/notaryproject.dev#209]
![image](https://github.com/notaryproject/notaryproject.dev/assets/95405559/6c029ac3-2fa7-4d3f-9fb8-1063590032ae)
The size of text here is 1rem while other content texts have a size of 1.2 rem. The difference can be perceived easily.
![image](https://github.com/notaryproject/notaryproject.dev/assets/95405559/3ab44536-9b51-4f9c-8be8-62ba26a5d325)

Also, the picture in the first image is almost illegible.

**Comment by PranitPatil03** [comment]
Hello @BabyElias 

I can work on this issue.

**Comment by BabyElias** [comment]
Hey @PranitPatil03  , I am a contributor myself. And want to work on this. Thank you so much for your interest!

**Comment by PranitPatil03** [comment]
hello @BabyElias 

While you are enhancing the mobile view, I noticed a disparity in font size within the Desktop view. I have included some screenshots as a reference. It would be greatly appreciated if you could address this too.

<details><summary>SS 1:</summary>
<p>

![screencapture-notaryproject-dev-2023-05-20-17_01_24](https://github.com/notaryproject/notaryproject.dev/assets/91155068/478a2967-4d0f-401b-97e6-b6b7428d80f8)

</p>
</details> 

<details><summary>SS 2:</summary>
<p>

![screencapture-notaryproject-dev-2023-05-20-17_01_24 (1)](https://github.com/notaryproject/notaryproject.dev/assets/91155068/edde1310-c0b9-4569-95e3-6b0d6e7e98dc)

</p>
</details>
