### ISSUE TITLE
Migrate Notary documentation content

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#21]
Move the existing Notary V1 documentation from https://github.com/notaryproject/notary/tree/master/docs into `/content/en/docs/notary` to consolidate all the documentation in one place.

**Comment by nate-double-u** [comment]
Adding p3-low label as we may not want to do this right away. Important for later.

**Comment by nate-double-u** [comment]
Updated reference to old repo location and refering to "Notary" instead of "V1."

**Comment by toddysm** [comment]
@nate-double-u Cleaning up issues. Is this something that still needs to be done?

**Comment by zr-msft** [comment]
To my knowledge, the content has been migrated over already. Closing for now, but feel free to reopen if i'm wrong
