### ISSUE TITLE
Update README by adding the steps to run the project in local system.

### ISSUE THREAD

**Issue by 0904-mansi** [notaryproject/notaryproject.dev#211]

**Comment by PranitPatil03** [comment]
hello @0904-mansi 

Based on my understanding, the current READ.me provides guidelines for running the project on a local machine. 
You can visit https://github.com/notaryproject/notaryproject.dev/blob/main/CONTRIBUTING.md to refer to these instructions. 

If my interpretation is incorrect and you are experiencing a different issue, please provide further clarification. Thank you 🙌
