### ISSUE TITLE
[FEATURE]: Add opengraph meta tags

### ISSUE THREAD

**Issue by ashutosh-rath02** [notaryproject/notaryproject.dev#215]
When a website is shared on social media we get to see a card which has an image, a website link, a title and/or a description.
I tried doing the same but could not get the card. This can be achieved by adding meta tags including these files. I can see the description, website link added but a image would enhance the card.
Additional screenshot: This is how the card looks now
![image](https://github.com/notaryproject/notaryproject.dev/assets/85403534/82edcc16-eea8-47da-8cf7-992807bb8379)

**Comment by Lucif3r-in** [comment]
@FeynmanZhou I want to work on this issue. Can you guide me where I can place the required meta tags?
