### ISSUE TITLE
update CLI reference automatically

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#216]
With new releases released, the [CLI reference](https://notaryproject.dev/docs/cli-reference/) becomes outdated. Is there a way to manually update it? Or can we add versioning for CLI reference?

@zr-msft @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Currently, we have to manually update it. It requires additional development to support automatic updates for CLI reference docs. We will introduce version control to the documentation site after Notation v1.0.0.

**Comment by zr-msft** [comment]
@FeynmanZhou  @yizha1 lets discuss the best way to approach this. 

I'm working on a PR to the notation repo that builds on the example you all provided for using cobra combined with some built-in text processors. My hope is that CLI ref docs can be generated at the same time as the CLI binary and added to the docs as-is.

**Comment by nishchay-veer** [comment]
@FeynmanZhou can you assign this to me ?

**Comment by zr-msft** [comment]
@nishchay-veer Thanks for reaching out, i'm already working on a PR for this so I've assigned it to myself. Sorry for the confusion.
