### ISSUE TITLE
[FIX] - Navbar opacity

### ISSUE THREAD

**Issue by ashutosh-rath02** [notaryproject/notaryproject.dev#217]
Description:
The current implementation of the navbar on the website suffers from a transparency issue at the HeroSection and Collaboration component, leading to reduced readability and visual disturbance. This issue significantly affects the user experience and hampers the accessibility of the navigation elements.

Video Attachment::

https://github.com/notaryproject/notaryproject.dev/assets/85403534/25ad4f33-5889-4356-a816-1a6307e96e06

Steps to Reproduce:
1. Open the website and scroll to the HeroSection or Collaboration component.
2. Scroll through the page and observe the transparency effect on the navbar.
3. Notice how the navbar elements blend with the underlying content, making them difficult to read and causing visual disruption.

Expected Behavior:
The navbar should not exhibit transparency at any section of the website, including the HeroSection and Collaboration component. It should maintain a solid background color(white) to ensure clear visibility and readability of the navigation elements, regardless of the scroll position.

**Comment by Lucif3r-in** [comment]
I am working on this issue.

**Comment by Lucif3r-in** [comment]
I am unable to stage the files for commit as it is in a submodule. Can anyone suggest me any solutions?
