### ISSUE TITLE
Migrate existing Notation documentation 

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#22]
Collect and migrate any existing, relevant, Notation documentation from https://github.com/notaryproject/notaryproject and https://github.com/notaryproject/notation, as well as any other relevant locations (please list below in comments), and put it in `/content/en/docs/notation` to help consolidate all the documentation in one place.

**Comment by nate-double-u** [comment]
We may need to decide on an information architecture before embarking on this issue.

**Comment by nate-double-u** [comment]
Updated reference to old repo location and referring to "Notation" instead of "V2."

**Comment by nate-double-u** [comment]
Given the _[How to document notary project content #101](https://github.com/notaryproject/notaryproject/issues/101)_ discussion, instead of migrating any Notation content now there should instead be a link in the top level navigation to the Notation Documentation in GitHub until it is ready to be migrated. 

Initially this menu item should link to https://github.com/notaryproject/notation#notation

**Comment by FeynmanZhou** [comment]
We have migrated most of the documents from other repos to the Notary website. 
https://github.com/notaryproject/notaryproject.dev/pull/75
https://github.com/notaryproject/notaryproject.dev/pull/80

**Comment by toddysm** [comment]
@nate-double-u Cleaning up issues. Is this something that still needs to be done? Also, seems dupe of #21

**Comment by FeynmanZhou** [comment]
I think we can close this as completed. If we detect any remaining work items, then reopen this one.
