### ISSUE TITLE
Information Architecture Proposal

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#23]
Please find an editable version of the IA Proposal here:
[notaryproject.dev Information Architecture Proposal](https://hackmd.io/@nate-double-u/H1JkSDYWF)

(Once the draft is complete, I'll bring it back here to be used for issue tracking)

**Comment by nate-double-u** [comment]
This is the structure suggested in https://github.com/cncf/techdocs/blob/main/assessments/0002-notary-project.md#information-architecture-2, _but_ it is incomplete, and up for discussion. Particularly the architecture around how `/docs` should work with `V1` and `V2` documentation.

**Comment by nate-double-u** [comment]
Based on discussions last week, I'd like to suggest that the docs get organized into 3 sections, one each for TUF, Notary, and Notation. (This would replace the V1/V2 folder organization we started with).

**Comment by nate-double-u** [comment]
Will each project's documentation set require its own versioning?

**Comment by nate-double-u** [comment]
I've added TUF, Notary, & Notation to the Top Nav section. I've removed Getting Started from the top nav as i'm not sure which project it would be referring to any longer.

**Comment by nate-double-u** [comment]
The _Contributing_ (`/contributing`) page may need to be split into three or four contributing pages. One each for TUF, Notary & Notation, and then potentially a fourth for contributing to the documentation/website.

**Comment by nate-double-u** [comment]
Rather than having an infrastructure that only I can edit, I've created a hackmd.io note to manage this, that way multiple people can edit/make suggestions/comment.

[notaryproject.dev Information Architecture Proposal](https://hackmd.io/@nate-double-u/H1JkSDYWF)

**Comment by toddysm** [comment]
@zr-msft I will use the HackMD @nate-double-u linked above to collaborate on the information architecture.

**Comment by zr-msft** [comment]
@toddysm I feel like the information architecture has been sorted out for now. Any objections to closing?

**Comment by FeynmanZhou** [comment]
> @toddysm I feel like the information architecture has been sorted out for now. Any objections to closing?

@zr-msft  +1. @nate-double-u Shall we close this issue?

**Comment by nate-double-u** [comment]
I agree, this can be closed.On Mar 2, 2023, at 7:51 AM, Feynman Zhou ***@***.***> wrote:﻿

@toddysm I feel like the information architecture has been sorted out for now. Any objections to closing?

@zr-msft  +1. @nate-double-u Shall we close this issue?

**Comment by zr-msft** [comment]
Thank you @FeynmanZhou  and @nate-double-u 

closing
