### ISSUE TITLE
Nav bar is see through in some parts of the website

### ISSUE THREAD

**Issue by starlightknown** [notaryproject/notaryproject.dev#236]
Not sure what's causing this but when I scroll through the website, we can see other text too through the nav bar in some sections. 
Here's the attached gif which shows the behavior. 

https://github.com/notaryproject/notaryproject.dev/assets/74637789/fdd2ea25-1c9e-4a62-be88-f0dc84bed445

**Comment by starlightknown** [comment]
same for other resolutions but here it's not nav bar. 
<img width="596" alt="image" src="https://github.com/notaryproject/notaryproject.dev/assets/74637789/caa1ea38-1fbc-49d6-839c-46961d1845b8">

**Comment by PranitPatil03** [comment]
hello @starlightknown 

It's an important message about the latest update and has been placed at the top for maximum visibility. I believe this was done on purpose to ensure that all users are informed about the update. you can also check the issue #199 & PR #212

**Comment by starlightknown** [comment]
> hello @starlightknown
> 
> It's an important message about the latest update and has been placed at the top for maximum visibility. I believe this was done on purpose to ensure that all users are informed about the update. you can also check the issue #199 & PR #212

cool, I was also pointing to the navbar in web containing docs, roadmap etc. You can see how it looks different when you scroll from the section with youtube video till scenarios we fit in the video I attached

**Comment by PranitPatil03** [comment]
@starlightknown 

yes, There is a problem while scrolling the page, I have attached the screenshot for reference, you can check that.

<details><summary>the logo & navigation items are overlaps with the other elements </summary>
<p>
<img width="960" alt="Screenshot 2023-05-21 205924" src="https://github.com/notaryproject/notaryproject.dev/assets/91155068/187fe8dd-0682-44b6-87f0-fbac2de67092">

</p>
</details>
