### ISSUE TITLE
[Enhancement] Drop Shadow needed in Navbar for Division in UI

### ISSUE THREAD

**Issue by Pranjal7852** [notaryproject/notaryproject.dev#239]
<img width="843" alt="image" src="https://github.com/notaryproject/notaryproject.dev/assets/68412756/ed719575-5b11-4b63-a1fb-7d81451808e5">

***

Little Drop Shadow at the **bottom** panel will help navbar panel get differentiate from the main website.
making the navbar blur is also an solution to this problem ;-p

**Comment by PranitPatil03** [comment]
Can I work on this?
