### ISSUE TITLE
[Enhancement] Notary Favicon not visible in Dark Mode  🕶️ 

### ISSUE THREAD

**Issue by Pranjal7852** [notaryproject/notaryproject.dev#240]
<img width="395" alt="image" src="https://github.com/notaryproject/notaryproject.dev/assets/68412756/e4cc03b5-c76e-400a-b231-db8adb0d23f0">

adding a white border or background will help the logo to be visible on dark mode enabled devices

**Comment by PranitPatil03** [comment]
Can I work on this?
