### ISSUE TITLE
Make each blog card on homepage clickable

### ISSUE THREAD

**Issue by kayceeDev** [notaryproject/notaryproject.dev#247]
On the homepage, we have a card for each blog post rendered dynamically on the news and blogs section.

Ref: #202 

**Current Behaviour**
The blog card has a learn more button that takes the user to the blog details page.

**Expected Behaviour**
The blog card should also have the same behavior as the learn more button.
Clicking on the blog card should take the user to the blog details page.

See example:
*Upcoming and recent events* section on [grafana homepage](https://grafana.com/)

**Comment by PranitPatil03** [comment]
hello @kayceeDev 

May I work on this?
