### ISSUE TITLE
User guide for using experimental feature `Using Referrers API`

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#259]
There is a user guide for experimental feature OCI image layout, https://notaryproject.dev/docs/how-to/oci-image-layout/,

We should create a guide for another experimental feature `Using Referrers API` and link it to the introduction to experiment feature.

**Comment by FeynmanZhou** [comment]
@Vikash-8090-Yadav Thanks. Are you familiar with this feature?

**Comment by Vikash-8090-Yadav** [comment]
Hey @FeynmanZhou sir, currently am not familiar with this feature. If possible can u please provide the resource to learn asap?
Thanks!
