### ISSUE TITLE
Add example commands for both Unix-based system and Windows PowerShell

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#263]
There are some commands that are only used for Unix-based systems, such as the [Configure environment variables](https://notaryproject.dev/docs/how-to/registry-authentication/#configure-environment-variables-to-authenticate-to-an-oci-compliant-registry). We need to consider adding example commands for Windows PowerShell. It would be much more convenient and friendly for users who are using Notation CLI on a Windows computer.

Another related discussion thread is https://github.com/notaryproject/notaryproject.dev/pull/196#discussion_r1205004644

**Comment by Vikash-8090-Yadav** [comment]
Hey @FeynmanZhou i would like to work on this, can u please assign me this.

**Comment by FeynmanZhou** [comment]
@Vikash-8090-Yadav Thanks for your interest! We can assign it to you.

**Comment by Vikash-8090-Yadav** [comment]
Hey @FeynmanZhou I created the alternative Windows command for the file mentioned above (Environment variable), I want to confirm that should I make the Windows command for all the files/ documents which are missing or the only ones u have mentioned above.
Thanks!

**Comment by FeynmanZhou** [comment]
> Hey @FeynmanZhou I created the alternative Windows command for the file mentioned above (Environment variable), I want to confirm that should I make the Windows command for all the files/ documents which are missing or the only ones u have mentioned above. Thanks!

@Vikash-8090-Yadav Sorry for the late response. We want to provide Windows Powershell commands for all documents.
