### ISSUE TITLE
Enhanced Confirmation Checks after Installing Notation CLI

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [notaryproject/notaryproject.dev#265]
I checked the installation guide for the notation CLI and I want to add the `How to check the Notation Cli after installing`  by using  `notation version` it's basically a confirmation check that the user has installed the Notation CLI correctly. Very helpful to first-time users.

Docs for improvement - https://notaryproject.dev/docs/installation/cli/
---

If this is legit then please assign this to me.
Thank You.

**Comment by FeynmanZhou** [comment]
It's nice to add this part. I just assigned it to you @Vikash-8090-Yadav . Thanks for your support!

**Comment by Vikash-8090-Yadav** [comment]
Thanks, @FeynmanZhou. Soon will raise PR for this.
