### ISSUE TITLE
Include Use Cases of Plugins available on Notation 

### ISSUE THREAD

**Issue by Miranlfk** [notaryproject/notaryproject.dev#268]
The docs on the website should include tutorials or links on how to use Notation supported plugins. Currently the supported plugin available is [azure-kv](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push?wt.mc_id=azurelearn_inproduct_oss_notaryproject). The user experience will be better if tutorials itself or links on how to use Notation compatible plugins are on the website.

**Comment by FeynmanZhou** [comment]
Thanks @Miranlfk . AWS Signer plugin and HashiCorp Vault plugin will be added soon.
