### ISSUE TITLE
Add Notation interactive tutorial to website 

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#272]
@kokamkarsahil helped us to add Notation interactive tutorial to Killercoda: https://killercoda.com/notaryproject/scenario/notation. It's super helpful for newbies to learn and get started with Notation CLI in a browser within just a few minutes. We could add this interactive tutorial to the Notary website:

1. Add the tutorial entry on the landing page. We can replace this button with this entry and name it `Try it` or `Demo`.
![image](https://github.com/notaryproject/notaryproject.dev/assets/40452856/678941c2-763c-48fe-8072-1f1926f7e5a7)

2. Add the interactive tutorial link in https://notaryproject.dev/docs/quickstart/

**Comment by kokamkarsahil** [comment]
Sure, thanks for the mention happy to help out, I would like to work on this! Can you assign this issue to me!

Thank you!

**Comment by FeynmanZhou** [comment]
Thanks! Assigned to @kokamkarsahil . Could you also update the Notation version to v1.0.0-RC.7 at https://killercoda.com/notaryproject/scenario/notation?

**Comment by kokamkarsahil** [comment]
> Thanks! Assigned to @kokamkarsahil . Could you also update the Notation version to v1.0.0-RC.7 at https://killercoda.com/notaryproject/scenario/notation?

Sure, I had updated the version to `v1.0.0-RC.7`
