### ISSUE TITLE
Improve registry authentication document with more information

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#276]
Triggered by issue https://github.com/notaryproject/notation/issues/696, we need to provide more information and clarity on [registry authentication](https://notaryproject.dev/docs/how-to/registry-authentication/). Here is some information:

### Why do we need a credentials store?

Users need to enter credentials every time they interact with a registry if credentials are not stored. However, storing credentials in plaintext is not secure because anyone can read them including attackers. Notation uses a credentials store to store the user’s credentials securely, especially in production environments. 

#### Option1: Configure credentials store in Notation configuration file

Users can configure credentials store in Notation configuration file `config.json`. For example:
```
{
        "credsStore": "desktop.exe"
}
```

In the above example, `desktop.exe` is the Docker credential store installed in Windows.

#### Option2: Use credentials store configured for docker engine

Notation can use credentials store configured for docker engine. This is especially useful for users who installed Docker in the system, normally credentials store will be installed by docker together. The credentials store can be found in `$HOME/.docker/config.json`, for example,

```
{
  "credsStore": "desktop.exe"
}
```
See [docker document](https://docs.docker.com/engine/reference/commandline/login/#configure-the-credentials-store) for details.

### What does Notation use the credentials store for?

- `notation login` write credentials into credentials store after authenticating with registries successfully.
- `notation logout` removes credentials from credentials store
- `notation sign` reads credentials from credentials store, and use credentials to authenticate with registries
- `notation verify` reads credentials from credentials store, and use credentials to authenticate with registries
- `notation inspect` reads credentials from credentials store, and use credentials to authenticate with registries
- `notation ls` reads credentials from credentials store, and use credentials to authenticate with registries

#### How Notation works if users configure credentials store in both notation config and docker config.

If users configure credentials store in both notation config.json and docker config.json, Notation will use the one configured in Notation config.json. 

#### How Notation works if users didn't configure any credentials store in notation and docker configuration

Notation will look for the native store on each of the platforms, i.e. “osxkeychain” on macOS, “wincred” on windows, and “pass” on Linux. If none of these stores exist, then `notation login` will fail to store the credentials.

#### How Notation works if there is no credential store present on the platform.

If no credential store is present on the platform, Notation cannot write the credentials. `notation login` will fail. Users should install the credential store accordingly. 

However, in this case, Notation can still read plaintext credentials from notation `config.json` or docker `config.json` if they are present, which means `notation sign/verify/ls/inspect` commands could still work.

Users can manually add plaintext credentials in base64 encoding in Notation `config.json`. This is not secure and not recommended.

For platforms with docker installed, the default behavior is that with a successful `docker login`, Docker stores the credentials (i.e. password) in base64 encoding in the config file if no credential store is present on the platform, see [docker document](https://docs.docker.com/engine/reference/commandline/login/#default-behavior)

Notation will first read credentials from notation `config.json`, then docker `config.json`, if credentials didn't exist in both config files, notation sign/verify/ls/inspect commands will fail.

#### Do I need to always use `notation login` before using other notation commands "notation sign/verify/ls/inspect"?

If you have `docker login` successfully, you can run notation commands "notation sign/verify/ls/inspect" directly.

#### Will `notation logout` remove credentials from the credential store used by Notation?

Yes.

**Updated** Note: If credentials stores are configured in both Notation config file and docker config file. Notation will remove credentials from the credentials store that is configured in Notation config only.

### Any other methods for authentication with registries?

If you don't want to use credentials store, install docker, or manually update notation `config.json`, you can use environment variable for authentication, see [doc](https://notaryproject.dev/docs/how-to/registry-authentication/#configure-environment-variables-to-authenticate-to-an-oci-compliant-registry). This is not recommended in the production system.

/cc @shizhMSFT @iamsamirzon @priteshbandi @FeynmanZhou @toddysm

**Comment by zr-msft** [comment]
@yizha1 can you provide the following config example snippets:

1. notation config.json with a configured credStore.
2. notation config.json with base64 username/pw stored

**Comment by yizha1** [comment]
@zr-msft  Please take a look at this [summary](https://github.com/notaryproject/notation/pull/712#issuecomment-1584042555). This is the latest behavior implemented. I will update my issue description accordingly.

**Comment by yizha1** [comment]
> @yizha1 can you provide the following config example snippets:
> 
> 1. notation config.json with a configured credStore.
> 2. notation config.json with base64 username/pw stored

```
{
  "auths": {
    "<registry>": {
      "auth": "<base64encoded>",
    }
  },
  "credsStore": "<credentials_store_name>"
}
```

for example:

```
{
  "auths": {
    "ghcr.io": {
      "auth": "YYMDCDFg=",
    }
  },
  "credsStore": "desktop.ext"
}
```

**Comment by yizha1** [comment]
@shizhMSFT  Please help to review the issue and PR based on the recent PR changes on credentials handling. This issue is to update the registry authentication document on website

**Comment by shizhMSFT** [comment]
Although `notation` supports `auths` field, it should not be used except glass-breaking scenarios.

**Comment by zr-msft** [comment]
Thank you @yizha1 

Can you provide more context for what value(s) should be base64 encoded for the `auth` field in the config file? 

Is it just the password? an auth token? `username:password`?
