### ISSUE TITLE
Publish security audit reports on notary website

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#280]
We need to publish security audits report on notary website, so that users can view the latest report as well as history reports.

The reports we had for now:

- Two security audits: https://github.com/notaryproject/notary#security-audits
- fuzzing audit: https://github.com/notaryproject/notaryproject/blob/main/security/reports/fuzzing/ADA-fuzzing-audit-22-23.pdf

There will be a new security report published in the upcoming week, we can add it later.

cc: @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Let's design and create an entry for `Security` on the top menu. I think the link to the Threat Model doc should also be added to the page later.

**Comment by FeynmanZhou** [comment]
Hi @sanjayk0508, could you pls help take this issue?

**Comment by sanjayk0508** [comment]
Sure @FeynmanZhou , you can assign me this issue.

**Comment by FeynmanZhou** [comment]
Close this issue since it is completed by #302
