### ISSUE TITLE
Update the README for the repository

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notaryproject.dev#288]
I propose to update the README.md file for the repository with the following information:
- link to the overview of the organization
- purpose of the repository
- is it in active development or not, is it archived or not, any reasons for that
- links to relevant documentation (security audits, web site, design documents, etc.)

**Comment by sanjayk0508** [comment]
I agree as well. The `README.md` file would benefit from more detailed information and a more organized structure. I will take on the task of improving it.

**Comment by FeynmanZhou** [comment]
@sanjayk0508 Thanks for your interest. I just assigned this issue to you
