### ISSUE TITLE
Write contributor guides

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#29]
- [ ] Code contribution guide
- [ ] Documentation contribution guide

**Comment by dtzar** [comment]
https://contribute.cncf.io/maintainers/github/templates/required/contributing/

**Comment by FeynmanZhou** [comment]
I can self-assign this issue.

**Comment by toddysm** [comment]
@FeynmanZhou would you mind linking HackMD doc with the draft to collaborate on?

**Comment by zr-msft** [comment]
We have a https://github.com/notaryproject/notaryproject.dev/blob/main/CONTRIBUTING.md so considering this issue resolved. Closing for now
