### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notaryproject.dev#291]
After reading through the [Troubleshooting](https://notaryproject.dev/docs/troubleshooting/), I think we could improve on following:
1. I could see several usages of `Notary` within this doc. Should we change them to `Notation`?
2. Under [when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer), in ```If you have multiple trust policies in trustpolicy.json file, confirm you are using the correct trust policy for this artifact.``` We should provide a way of how to confirm this. We could add `if -v flag is set up, the trust policy been used by verify will be displayed in the log.` 
3. Also under [when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-signature-is-not-produced-by-a-trusted-signer), `notation cert show` command displays SHA256 instead of SHA1 thumbprints now.
4. Under [when-i-verify-an-artifact-i-get-the-error-error-open-homeconfignotationtrustpolicyjson-no-such-file-or-directory](https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-error-open-homeconfignotationtrustpolicyjson-no-such-file-or-directory), we should provide solutions to this issue. For example, telling the user to use `notation policy show` and/or `notation policy import` to set up a trust policy configuration.

**Comment by Two-Hearts** [comment]
@yizha1 @FeynmanZhou Here are some potential improvements that we could apply to the doc. Thanks.

**Comment by FeynmanZhou** [comment]
Thanks @Two-Hearts for the feedback. @Roseline-Bassey Would you mind taking this issue as a part of the troubleshooting guide improvement plan?

**Comment by Roseline-Bassey** [comment]
Yes, I'd love to work on this. @FeynmanZhou
