### ISSUE TITLE
[Docs] The readme.md is short and doesn't explain much about the project

### ISSUE THREAD

**Issue by 1Shubham7** [notaryproject/notaryproject.dev#301]
The readme of the project lacks comprehensive information, making it difficult for new newcomers to understand the project through readme.

![notary1](https://github.com/notaryproject/notaryproject.dev/assets/116020663/8aa1be55-4015-4af7-b3f5-e5f6f50a143e)

We can add the following points without disturbing the current content:

- Notary - Intro
- Get started
- Support 
- Community
- Contributing
- License

add some more minor things.

**Comment by 1Shubham7** [comment]
Please allow me to work on this issue.

**Comment by sanjayk0508** [comment]
Hi Shubham! Thank you for showing interest in it. A PR (#295 ) has already been made regarding this issue, and it is currently under review. If you would like to help us, you can review the PR or provide some suggestions. Thank you!

**Comment by 1Shubham7** [comment]
Yes @sanjayk0508 , I would love to .

**Comment by FeynmanZhou** [comment]
@1Shubham7 Thanks. Let's concentrate and work on #295 first.
