### ISSUE TITLE
Improve Plugin Development documentation

### ISSUE THREAD

**Issue by zosocanuck** [notaryproject/notaryproject.dev#305]
Hi,

Per the community call on July 6, 2023 (see [notes](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Notes)) it would be great to improve the overall plugin development experience, either via separate dedicated documentation or improved readability of the [plugin extensibility spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md).

From my perspective, the Notary V2 [specs](https://github.com/notaryproject/notaryproject/tree/main/specs) are well articulated and have been very helpful during my journey as a plugin developer.  

Suggested Improvements:

- Improved guidance around the Signature Generator capabilities, especially when choosing `SIGNATURE_GENERATOR.RAW` vs. `SIGNATURE_GENERATOR.ENVELOPE`.  Include advantages/disadvantages allowing the plugin developer to make an informed decision especially when it comes to compatibility during early stage development.
- Provide a reference plugin implementation for `SIGNATURE_GENERATOR.ENVELOPE` in a popular language such as golang, to help bootstrap development efforts.  In my case, I ended up pulling sample code from [notation-go-core/signature/jws](https://github.com/notaryproject/notation-core-go/blob/main/signature/jws/envelope.go) to get going.
- Improve documentation as well as provide code samples around how plugin developers implementing `SIGNATURE_GENERATOR.ENVELOPE` should generate vendor-specific extended attributes to be consumed by a plugin that implements `SIGNATURE_VERIFIER.TRUSTED_IDENTITY` and needs to verify vendor-specific attributes during the verification workflow.
- Dedicated Plugin Developer documentation with reference implementations in select languages such as golang, .NET, etc.

**Comment by FeynmanZhou** [comment]
JFYI, Notation Hashicorp Vault plugin might be an example for the plugin development https://github.com/notaryproject/notation-hashicorp-vault

**Comment by FeynmanZhou** [comment]
This request also needs suggestions from @notaryproject/notaryproject-notation-go-maintainers and @notaryproject/notaryproject-notation-core-go-maintainers.
