### ISSUE TITLE
Proposed Documentation Structure for Notary Project

### ISSUE THREAD

**Issue by Roseline-Bassey** [notaryproject/notaryproject.dev#306]
Hi, Notary Maintainers

I'd like to request your feedback on the structure of the proposed docs.
Here's an overview of the proposed structure:

Project Overview
Contributing.md
Notation

- Quick-start guides.md
- Installation guides
- Tutorials
- How-to-guides
- Concepts
- CLI Reference
- Glossary.md

Troubleshooting
Developer Documentation
Frequently Asked Questions

The link to the Google docs can be found [here](https://docs.google.com/document/d/15y_U7Yyqlysw-rJDolZct5wjhlZHpoLeBvqVod6OTcs/edit)

**Comment by zr-msft** [comment]
This issue has been resolved by #312
