### ISSUE TITLE
The Notary Fuzzing Audit report link is not displayed after a new link added

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#307]
The Notary Fuzzing Audit report link is not displayed at https://notaryproject.dev/security-audit/ after a new report link ada logics 2023 - notation security audit added. Should the new report link be placed in another file instead of "content/en/security-audit/audit-2023-1.md"? @sanjayk0508 Could you pls help look into this issue and fix it?
 
See related changes in https://github.com/notaryproject/notaryproject.dev/pull/302/files

**Comment by sanjayk0508** [comment]
Yes, when creating a new link, it should be added in a new `.md` file, for example, `content/en/security-audit/audit-2023-2.md`. I will submit a PR to fix it.
