### ISSUE TITLE
Describe the difference between notary, TUF, Notary Project specification, and notation in faq.md

### ISSUE THREAD

**Issue by Roseline-Bassey** [notaryproject/notaryproject.dev#323]
Describe what is what, what it means, how it works, and how it is different from the others.

**Comment by yizha1** [comment]
@Roseline-Bassey I think this issue was created per https://github.com/notaryproject/.github/issues/35#issuecomment-1642938826. The priority is P0, and will you work on this issue?

**Comment by Roseline-Bassey** [comment]
Yes, I am working on the issue. @yizha1

**Comment by FeynmanZhou** [comment]
@Roseline-Bassey Thanks. These terminologies should be documented in the Glossary chapter.

**Comment by Roseline-Bassey** [comment]
The Glossary folder is part of this PR #312 which is still under review.  Should I submit a different PR for the Glossary file? Just for clarity, would there be need to document the difference between these terminologies in the faq.md file too?  @FeynmanZhou

**Comment by FeynmanZhou** [comment]
> The Glossary folder is included in this PR#312 which is still being reviewed. Should I submit a separate PR to create the glossary.md file? Also, for clarification, would it be necessary to still document the difference between these terminologies in faq.md as well? @FeynmanZhou

Let's do it in a separate PR.
