### ISSUE TITLE
Update installation guide for Notation v1.0.0

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#324]
Notation v1.0.0 will be released in a few days after the naming issue is resolved. We will need to update the installation guide accordingly.
- [x] Update the Notation version from v1.0.0-rc.7 to v1.0.0
- [x] There will be multiple installation binaries available at multiple package managers/platforms including Homebrew, Snap, and Winget after v1.0.0. We need to update the installation guide accordingly when those binaries are available.
- [ ] Move the checksum validation process to a separate section in https://notaryproject.dev/docs/installation/cli/.
- [ ] Redesign the installation page to support multi-platform and provide tabs that allow users to switch to the different platform.

**Comment by zr-msft** [comment]
PR #281 updates binary version, links, and banner

**Comment by yizha1** [comment]
@FeynmanZhou I think this issue can be closed
