### ISSUE TITLE
Update website for naming issues

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#325]
I reviewed the documents on website, and found the following containing `Notary` term, and thus need to be updated per the approved [proposal](https://github.com/notaryproject/.github/issues/35#issuecomment-1642938826).

- https://notaryproject.dev/docs/overview/
- https://notaryproject.dev/docs/faq/#what-registries-are-compatible-with-notary
- https://notaryproject.dev/docs/installation/
- https://notaryproject.dev/docs/tutorials/
- https://notaryproject.dev/docs/tutorials/trust-policy/
- https://notaryproject.dev/docs/how-to/
- https://notaryproject.dev/docs/concepts/

**Comment by zr-msft** [comment]
@yizha1 @toddysm can you clarify that when referring to the signature or envelope is it *Notary signature* or *Notary Project signature*?

For example:
- Notary envelope can support payloads other than JSON, like binary.
- Notary signature requires support for unsigned attributes.

**Comment by yizha1** [comment]
> @yizha1 @toddysm can you clarify that when referring to the signature or envelope is it _Notary signature_ or _Notary Project signature_?
> 
> For example:
> 
> * Notary envelope can support payloads other than JSON, like binary.

Notary Project signature envelope

> * Notary signature requires support for unsigned attributes.

Notary Project signature

**Comment by FeynmanZhou** [comment]
Also, the project brand name is `Notary Project` instead of `The Notary Project`.
