### ISSUE TITLE
Documentation for tanzu podcast

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#342]
This issue is to ask for documentation of nuggets from the tanzu podcast  https://tanzu.vmware.com/content/videos/enlightning-ensuring-software-authenticity-introduction-to-notary-project

**Comment by zr-msft** [comment]
Based on my review of the podcast and reviewing the docs, i think we should add the following concepts/details to the docs:
- Provide details and explanations around the policy enforcement levels
- In the overview:
  - explain Authenticity and Integrity
  - call out artifact portability
  - list the pros/benefits of using notary project
- Provide some details about attestations and signing them
- Provide an overview about using a certificate from a CA
- Provide some details about revocation and how notation handles it

@toddysm @sajayantony @FeynmanZhou @yizha1 let me know what you think then i'll start scoping the work

**Comment by yizha1** [comment]
Thanks @zr-msft
Maybe we can add one more item about extensibility.

**Comment by yizha1** [comment]
Closed as the podcast is available at https://notaryproject.dev/blog/2023/notary-enlightning-podcast/
