### ISSUE TITLE
Document for new trust store and trust policy experience

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#346]
Update existing document or create new document for Notation v1.1.0 feature "Improve experience of managing trust store and trust policy", which include the following enhancements:

- Trust store: https://github.com/notaryproject/notation/issues/631
- Trust store: https://github.com/notaryproject/notation/issues/609
- Trust store: https://github.com/notaryproject/notation/issues/772
- Trust policy: https://github.com/notaryproject/notation/issues/769
- Trust policy: https://github.com/notaryproject/notation/issues/653
- Trust policy: https://github.com/notaryproject/notation/issues/590

**Comment by zr-msft** [comment]
Per description, adding to 1.1.0 milestone
