### ISSUE TITLE
New document for Notation GitHub Action

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#347]
Create a new how-to or tutorial for [Notation GitHub Action](https://github.com/notaryproject/notation-action)

**Comment by zr-msft** [comment]
@yizha1  should this be a part of the 1.1.0 milestone?

**Comment by yizha1** [comment]
@zr-msft I think so. @FeynmanZhou  what do you think?

**Comment by FeynmanZhou** [comment]
@zr-msft It's not a part of 1.1.0 milestone. [Notation GitHub Action](https://github.com/notaryproject/notation-action) is not a Notation built-in feature so we don't need to inherit the same version control from Notation. 

We recently published the Notation GitHub Actions to [GitHub Marketplace](https://github.com/marketplace/actions/notation-actions) and create basic guideline in README. Could you pls help create a new doc on the website https://notaryproject.dev/docs/user-guides/how-to/?

**Comment by zr-msft** [comment]
@FeynmanZhou i thought we were using milestones to track the work happening leading up to the 1.1.0 Notary release, regardless of if the feature itself was firmly tied to a version of Notation. 

Using milestones gives a clearer idea of the current priorities as opposed to informally tracking across multiple other mediums like chat and email
