### ISSUE TITLE
Fix the broken link on the landing page

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#351]
This link is broken after the doc directory is restructured. The URL https://notaryproject.dev/docs/quickstart/ should be replaced by https://notaryproject.dev/docs/quickstart-guides/quickstart/.
![image](https://github.com/notaryproject/notaryproject.dev/assets/40452856/5be1f21d-f9d4-4930-9f00-96a25e9ec399)

**Comment by FeynmanZhou** [comment]
@Roseline-Bassey would you mind fixing this issue and check if there are any other broken links after restructure? Thanks

**Comment by Roseline-Bassey** [comment]
Sure, I'll fix the issue and check for any other broken links. @FeynmanZhou

**Comment by FeynmanZhou** [comment]
@Roseline-Bassey Thanks.
