### ISSUE TITLE
The documentation about credentials store can be improved

### ISSUE THREAD

**Issue by Wwwsylvia** [notaryproject/notaryproject.dev#353]
I was reading the [documentation about credentials store](https://notaryproject.dev/docs/user-guides/how-to/registry-authentication/#configure-a-credentials-store) and found that the following parts can be improved:

1. 

> A credentials store is a secure location that stores your credentials, such as usernames and passwords. Operating systems often include a default credentials store, such as osxkeychain on macOS or wincred on Windows. You can also use a third-party credentials store, such as [pass](https://www.passwordstore.org/).

`notation` relies on docker credential helpers to interact with the credentials store. It's better to have a link to the [docker credentials helper documentation](https://docs.docker.com/engine/reference/commandline/login/#credential-stores) which introduces what credentials helpers are supported and how to install them.

2. 

> To configure a credentials store in the notation configuration file, add a credStore to the [notation config.json file](https://notaryproject.dev/docs/user-guides/how-to/notary-project-concepts/). The following example shows osxkeychain as the configured credentials store.

This paragraph references the [notation config.json file](https://notaryproject.dev/docs/user-guides/how-to/notary-project-concepts/) page. However, that page does not document anything about the [`credsStore`](https://docs.docker.com/engine/reference/commandline/login/#configure-the-credential-store) and the [`credHelpers`](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) fields.

**Comment by FeynmanZhou** [comment]
This issue is still valid so reopen this one
