### ISSUE TITLE
Unexpected page-not-found error

### ISSUE THREAD

**Issue by patrcoff-kainos** [notaryproject/notaryproject.dev#354]
URL: https://notaryproject.dev/docs/installation/cli/
Expected page: Installation guide as linked from both MS docs and your own getting started guide

**Comment by FeynmanZhou** [comment]
I also found some broken links by scanning the whole website with https://www.deadlinkchecker.com/website-dead-link-checker.asp

![image](https://github.com/notaryproject/notaryproject.dev/assets/40452856/81f3f21d-1419-4a8d-86cc-65c35cb1be2a)

Will raise a PR to fix it.
