### ISSUE TITLE
Unexpected page-not-found error

### ISSUE THREAD

**Issue by pbijjalaacn** [notaryproject/notaryproject.dev#360]
URL: https://notaryproject.dev/docs/quickstart/
Expected page: quick start guide from https://notaryproject.dev/docs/quickstart-guides/quickstart/

**Comment by FeynmanZhou** [comment]
Thanks for reporting this issue. We recently restructured the doc directory structure but there might be any broken links are missing. Where did you find the URL reference https://notaryproject.dev/docs/quickstart/  ?
