### ISSUE TITLE
Support keyword search on the website

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#361]
We need to support searching content including docs and blogs on the Notary Project website so that users can easily find their expected content by searching keywords.

Algolia provides [free search program](https://www.algolia.com/for-open-source/) for open source projects. We can apply for that program and integrate Algolia search on the website.

**Comment by PranitPatil03** [comment]
Hello @FeynmanZhou 👋

Certainly, integrating a search feature is a valuable addition to improve the overall user experience on the Notary Project website. Algolia's free search program for open source projects aligns perfectly with our goal.

To proceed, we'll follow these steps:

1. **Register for Algolia's Free Search Program** : Initiate the process by signing up for Algolia's free search program

 2.  **Create an Index for the Website and Documentation** : Define an index structure for both the website and documentation. An index serves as a database table where Algolia efficiently stores and indexes the data for optimized search results.

 3. **Install Algolia JavaScript API Client** : Incorporate the Algolia JavaScript API client into our project. This client will empower us to seamlessly implement the search feature, providing users with a fast and accurate search experience.

 4. **Integrate with Website UI** : Once the index is set up and the Algolia client is integrated, we'll seamlessly embed the search functionality into the website's user interface. 

Considering the complexity, I propose creating a demo search feature with limited data initially. This allows us to validate the functionality. Looking forward to contributing to this enhancement.
