### ISSUE TITLE
Link testing and Makefile: special setup using symlinks is no longer needed

### ISSUE THREAD

**Issue by chalin** [notaryproject/notaryproject.dev#37]
See the etcd.io Makefile for an example of the kind of simplification that is possible.

**Comment by chalin** [comment]
Let's wait for htmltest v0.14.0+ to be released before fixing this. Ref.: https://github.com/wjdp/htmltest/discussions/174

**Comment by toddysm** [comment]
@nate-double-u Is this something that still needs to be done?
