### ISSUE TITLE
Missing web page for verification on k8s

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#373]
It seems this document was missed in the Notary Project website after website structure overhaul

https://github.com/notaryproject/notaryproject.dev/blob/main/content/en/docs/how-to/verify.md

cc: @FeynmanZhou

**Comment by FeynmanZhou** [comment]
We will need to add `/user-guides` to the URL. @Roseline-Bassey Would you mind taking this issue? Thanks

**Comment by Roseline-Bassey** [comment]
I have submitted a PR to fix this issue. @FeynmanZhou & @yizha1
