### ISSUE TITLE
Update the Notary logo with new Notary Project logo

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#391]
CNCF shared the new logo design of Notary Project with us recently. There are some places we need to update with the new logo. For the term "Notary" used on the CNCF Artwork and Landscape, we also need to update it to Notary Project accordingly.

- [Notary Project website](https://notaryproject.dev/)
- [CNCF Artwork](https://github.com/cncf/artwork/blob/main/examples/incubating.md#notary-logos)
- [CNCF Landscape](https://github.com/cncf/landscape)

**Comment by FeynmanZhou** [comment]
Attaching the new logo here: [notary_project_logo.zip](https://github.com/notaryproject/notaryproject.dev/files/14527551/notary_project_logo.zip)

**Comment by Roseline-Bassey** [comment]
I’d like to work on this issue. @FeynmanZhou

**Comment by FeynmanZhou** [comment]
> I’d like to work on this issue. @FeynmanZhou

Thank you for your help! @Roseline-Bassey

**Comment by Roseline-Bassey** [comment]
> > I’d like to work on this issue. @FeynmanZhou
> 
> Thank you for your help! @Roseline-Bassey

My pleasure.

**Comment by Roseline-Bassey** [comment]
I have submitted a PR to the CNCF Artwork repository to update the logos. Here's the link: https://github.com/cncf/artwork/pull/469
