### ISSUE TITLE
Add Bitnami as a Notation adopter and a blog entry

### ISSUE THREAD

**Issue by beltran-rubo** [notaryproject/notaryproject.dev#394]
As Notation is supported in DockerHub https://github.com/notaryproject/notaryproject.dev/pull/393 The Bitnami team is working on signing the containers and Helm charts in DockerHub using Notation. E.g. https://hub.docker.com/r/bitnami/postgresql/tags

This issue is to create a blog entry and add Bitnami as adopter of Notation as well.

**Comment by FeynmanZhou** [comment]
I am super excited to see Bitnami adopts Notation to sign hundreds of OSS images. PRs for the adopter information and blog post are welcome. /cc @notaryproject/notaryproject-governance-maintainers

**Comment by yizha1** [comment]
Big thanks to @beltran-rubo and the crew! Awesome news. Really appreciate you picking Notary Project and Notation for your signing needs. Looking forward to further collaboration.
