### ISSUE TITLE
Complete file setup for proper use of cncf/docsy

### ISSUE THREAD

**Issue by chalin** [notaryproject/notaryproject.dev#43]
Ref. https://github.com/etcd-io/website/issues/431

**Comment by toddysm** [comment]
@nate-double-u Is this still something that needs to be done?

**Comment by nate-double-u** [comment]
If we're moving to the latest version of Docsy, I think it may be easiest to use NPM to install and manage it. @chalin, thoughts?

**Comment by chalin** [comment]
It depends on how many file overrides there are: if there are many, then having a Notary-specific branch would be advisable. We should minimize overrides -- OTel has very few, for example. Regardless, keeping it as a submodule for now, might make sense. We can always switch to using Docsy via NPM later. With more recent versions of Docsy, projects no longer require recursive submodules, which is already an improvement.
