### ISSUE TITLE
Homepage & Community page: top-nav can be difficult to read due to transparency

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#45]
Pages with block/cover have this issue:
<img width="1454" alt="Screen Shot 2021-09-22 at 11 59 32 AM" src="https://user-images.githubusercontent.com/4453979/134405474-687cd10c-1b92-49e8-96dd-3764d98094f8.png">
<img width="1237" alt="Screen Shot 2021-09-22 at 11 59 46 AM" src="https://user-images.githubusercontent.com/4453979/134405491-59c3d836-9685-492d-8f9e-3cfbe08457c3.png">

Also see https://github.com/grpc/grpc.io/issues/866, https://github.com/etcd-io/website/issues/501.

**Comment by toddysm** [comment]
Hopefully this will get fixed with the new design work. Keeping as a bug

**Comment by zr-msft** [comment]
This appears to be fixed. Closing for now
