### ISSUE TITLE
Blog and Docs navbar entries are not shown as active when section pages are being viewed

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#61]
- [ ] Blog (see screenshot below)
- [ ] Docs

related: https://github.com/grpc/grpc.io/issues/895

### expected
<img width="1169" alt="Screen Shot 2021-11-09 at 3 34 01 PM" src="https://user-images.githubusercontent.com/4453979/141022664-5bbab766-8463-4905-827d-121eee5d5e5f.png">

### actual 
<img width="1169" alt="Screen Shot 2021-11-09 at 3 33 33 PM - 2" src="https://user-images.githubusercontent.com/4453979/141022933-ca5ed807-1789-4f8c-9504-bd21b82a7e82.png">

**Comment by nate-double-u** [comment]
Marking as "good first issue" as the [related issue](https://github.com/grpc/grpc.io/issues/895) has 2 PRs that show potential solutions.

**Comment by nate-double-u** [comment]
Another potential solution: https://github.com/gohugoio/hugo/issues/9150#issuecomment-965798975

**Comment by reddymahendra52** [comment]
I have checked the site. I can't seem to find the same error.

## Screenshots

### Community Page:
![Screenshot (20)](https://user-images.githubusercontent.com/61696212/143690711-0d539361-507d-4d4b-810e-5c050686b278.png)


### Blog Page:
![Screenshot (21)](https://user-images.githubusercontent.com/61696212/143690713-aae9542a-51f3-436c-a35f-aa5f3d158646.png)

**Comment by nate-double-u** [comment]
Hi @reddymahendra52, thanks for looking into this!

At the Blog level it works, but if you click into an article, the highlighting disappears (see https://notaryproject.dev/blog/2021/announcing-notation-alpha1/)

<img width="1281" alt="Screen Shot 2021-11-27 at 12 06 37 PM" src="https://user-images.githubusercontent.com/4453979/143720785-02fb902d-77c1-4316-b8e1-3f6bdbd4e760.png">

Same with the Docs -- it works at the highest level, but when you drill down then the highlighting turns off.
