### ISSUE TITLE
Bad security practice in example

### ISSUE THREAD

**Issue by Hades32** [notaryproject/notaryproject.dev#70]
The [announcement](https://github.com/notaryproject/notaryproject.dev/blob/main/content/en/blog/2021/announcing-notation-alpha1.md#L65-L67) contains this snippet
```bash
# Capture the digest of the SBOM, to sign it
SBOM_DIGEST=$(oras discover -o json \
                --artifact-type sbom/example \
                $IMAGE | jq -r ".references[0].digest")

notation sign $REPO@$SBOM_DIGEST
```
If I understand this correctly, this gets the digest to sign from a potentially public registry. So, in theory it would be possible for a malicious registry to modify the uploaded artifact before the signature process starts.
Isn't it possible to generate the digest locally?

**Comment by marcofranssen** [comment]
At least for docker images it is the case the digest is generated locally during the push operation.
This digest even keeps the same across registries/repositories.
Pushing one image to multiple registries/repositories will have the same digest.

The only downside is that OCI/Docker registries do not have an API that allows requesting all tags for a certain digest. So e.g. if you are pulling an image you usually do that via the tag `latest` or `v0.x.x` etc. When pulling the image you can then read the digest from the response.

I have been facing similar challenges when implementing SLSA provenance for docker images. We simply lack that API on OCI registries that allows to fetch tags related to a digest. https://github.com/philips-labs/slsa-provenance-action

**Comment by SteveLasker** [comment]
Closing as I believe this is covered.
FWIW, we do want to [support tag signing](https://github.com/notaryproject/notaryproject/issues/63)
