### ISSUE TITLE
Update docs to reflect Notary signs more than just containers

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notaryproject.dev#71]
The docs focused on the container ecosystem, as the primary usecase. However, there are two pivots we need to recognize in the docs.
1. Registries can store anything from containers, helm charts, debian packages, family photos to VM images
2. Notary can be used to sign things outside of the registry, including other package managers, files stored on shares. 

This issue is to document the breadth by which notary can be used.

**Comment by toddysm** [comment]
Will keep to consider in the documentation.

**Comment by zr-msft** [comment]
Based on spot-checking the docs, references to signing refer to *Artifacts*. If there are specific use cases beyond container image that should be included in the docs, i think those should be tracked individually. Closing for now, but please reopen if i missed something.
