### ISSUE TITLE
Automate notation cli commands

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notaryproject.dev#72]
The Notary Project cli docs could use some assistance with the list of commands and parameters for each `notation` command group.
Automating the list of commands and parameters from code would dramatically ease quick iterations.

We'll also want to add human docs to round the automation.

**Comment by toddysm** [comment]
Don't think this belongs to this repository. Commands are specified in the notaryproject/notation repository. Would recommend filing the issue there. Will close in a week if no further action is requested.

**Comment by SteveLasker** [comment]
Thanks Toddy,
While the apis are defined in the notation project, how can we document their usage in the site?  Some automation, perhaps?

**Comment by toddysm** [comment]
I may be confused what the ask here is. The CLI should have self-explanatory help for all commands. Is the ask here to publish the help to the web site automatically when a new build of the CLI is done?

**Comment by SteveLasker** [comment]
The ask is to have some amount of commands documented, similar to https://oras.land/cli/1_pushing/
where scenarios are documented, to show what series of commands can be used.

**Comment by toddysm** [comment]
@shizhMSFT Do you know what is the process to automate the publishing of the help commands to the notaryproject.dev if there is such automation possible?

**Comment by shizhMSFT** [comment]
> @shizhMSFT Do you know what is the process to automate the publishing of the help commands to the notaryproject.dev if there is such automation possible?

@yizha1 and @FeynmanZhou can help here. 

The `notation` CLI uses cobra as its CLI framework and thus we can generate CLI doc automatically using the build-in functions by cobra. However, the generated doc is not in a good shape and may need more attention to revise it. We are able to enhance it if we have sufficient dev resources.
