### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#76]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by toddysm** [comment]
@nate-double-u Is this completed or do we need to take any action to fix this? We have less than two weeks till the deadline.

**Comment by chalin** [comment]
I suspect that this hasn't been done yet (I can't check at the moment since I don't have access to Netlify).

**Comment by chalin** [comment]
I confirm that this hasn't been completed.

Also, all the builds for the past week or so (at least) have been failing, possibly because of this. @nate-double-u or I can look into this when I'm back at the office (Monday or Tuesday).

**Comment by chalin** [comment]
Seems to have started failing when the active Node.js LTS went from v16 to v18.

**Comment by nate-double-u** [comment]
I've gone in and changed the build image,

<img width="951" alt="Screenshot 2022-11-08 at 9 18 13 AM" src="https://user-images.githubusercontent.com/4453979/200632113-f2a9a105-ecb9-47db-9865-1a2ab7e9e921.png">

Previews are deploying correctly now: https://app.netlify.com/sites/notarydev/deploys/636a8f646026b21cb3b8ba87

**Comment by nate-double-u** [comment]
We should make sure that there are maintainers (or folks delegated by the maintainers) in the[CNCF Projects Netlify](https://app.netlify.com/teams/cncf-projects/overview) team so that these kinds of changes can be made by the Notary team.

/cc @SteveLasker

**Comment by chalin** [comment]
I'm glad that the image update fixed the build problems.
Can this be closed now @nate-double-u?
