### ISSUE TITLE
Notary project information architecture for the documentation section

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notaryproject.dev#88]
Filing this issue to discuss the information architecture for the notary documentation site. Note that this is not the whole notaryproject.dev site but just the docs section https://notaryproject.dev/docs/. There is already issue #23 for the overall site IA.

Here is an initial proposal for the docs IA:

### New Documentation Directory
Category | Documentsn | Status | Need   review existing docs? | refreshing 
-- | -- | -- | -- | -- 
Quick Start | Quick start | 1/1 | Yes | per new release
Installation   guides | Installation guide | 1/1 | Yes | per new release
Tutorials | * Sign a container image <br>        * using a local key for testing purpose<br>     * Sign a container image         using a key stored in Key vault (Azure Key vault or AWS KMS)<br>   * Sign artifacts (e.g SBOM file) stored in a registry<br>     * List artifacts and         associated signatures stored in a registry <br>    * Verify signatures using trust store and trust policy<br>    * Build a plugin <br> * Others: like Ratify validation | 0 |   | Per new feature
How-to guides | * Explain Directory         structure after installation of notation CLI <br>    * Configure signing keys <br>    * Configure a different         signature envelope <br>    * Configure trust policy <br>    * Configure trust store <br>    * Install/uninstall plugins | 0 |   | Per new feature
Concepts | Concept | 1/1 | Yes | per new release
Troubleshooting | Troubleshooting guide | 0/1 |   | Per new feature
Frequently asked   questions | FAQ | 1/1 | Yes | per new release
specifications | A page to add links to         each spec in different repos under notaryproject | 0 |   | Per new spec

CC:// @zr-msft @yizha1 @vaninrao10

**Comment by FeynmanZhou** [comment]
Spec audiences are developers. I think it's not necessary to add specifications to the website. We might keep the specifications in the https://github.com/notaryproject/notaryproject repo for single-source content maintenance.

**Comment by nate-double-u** [comment]
We may be able to simplify the top level docs with a structure like:
* Concepts
* Tasks
* Tutorials
* Reference

(kubernetes.io uses this structure to good effect: https://kubernetes.io/docs/home/)

Things like quick start, installation guides, and troubleshooting could go under Tasks.

Specifications and FAQs would probably go under Reference.

It's also worth noting that the folder structure under the the site may not be the same as the information architecture presented on the site pages themselves -- for instance, a getting started page can be organized under tasks but still be linked to the top nav on the landing page.

**Comment by zr-msft** [comment]
@nate-double-u usually i've seen quickstarts as their own top-level items or folder to increase visibility. Beyond having a cleaner top level of the TOC, do you have a strong feeling for mixing them with tutorials and the rest of the guides?

**Comment by nate-double-u** [comment]
> usually i've seen quickstarts as their own top-level items or folder to increase visibility.

I agree, but this is why I mention the separation of what gets displayed and what the underlying folder structure is -- they can be something other than 1 to 1. The quick start can be listed in the nav but still be stored in a deeper-level folder.

We should also consider what pages need to be versioned and make sure that the stuff that doesn't have to change every release gets pulled out and put into a higher-level folder.

> Beyond having a cleaner top level of the TOC, do you have a strong opinion or major benefit for mixing them with tutorials and the rest of the guides?

Having a cleaner top-level/nav is a good reason, but beyond that, it fits there logically.

**Comment by toddysm** [comment]
> Spec audiences are developers. I think it's not necessary to add specifications to the website. We might keep the specifications in the https://github.com/notaryproject/notaryproject repo for single-source content maintenance.

We should have a developer specific section that explains the concepts for people who want to implement tools using the libraries. We can move the specifications there. Though, this is not a priority for the documentation.

**Comment by FeynmanZhou** [comment]
> We should have a developer specific section that explains the concepts for people who want to implement tools using the libraries. We can move the specifications there. Though, this is not a priority for the documentation.

@toddysm Actually specs have been migrated to the website from https://github.com/notaryproject/notaryproject. If we want to maintain it on the website, I think we should remove the duplicated source at https://github.com/notaryproject/notaryproject.
