### ISSUE TITLE
Security policy for notation

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notaryproject.dev#94]
We need to write a security policy for Notation project.

**Comment by FeynmanZhou** [comment]
From my understanding, it should be a recommended trust policy JSON file with strict security configurations, like a best practice of TP, right?
If so, we can upload this JSON file to GitHub and provide a download link for users to easily download it to a target folder.

**Comment by FeynmanZhou** [comment]
Hi @zr-msft, could you pls help us to prepare for this guide?

**Comment by FeynmanZhou** [comment]
@toddysm  Zach has added a guide for Trust Policy in verification. Is this one meet your needs? https://notaryproject.dev/docs/tutorials/trust-policy/

**Comment by yizha1** [comment]
@FeynmanZhou  I think it's not for trust policy. it is like this https://github.com/notaryproject/notation/security/policy

**Comment by yizha1** [comment]
@toddysm should we move this issue to notaryproject, and let each sub-project refers to the same security policy file.
Here is an example from `containerd` project

The security policy as security.md is stored under `containerd/project`, and under `containerd/containerd` sub-repo, the security policy under security tab points to the one under `containerd/project`.

**Comment by toddysm** [comment]
The following PR has a draft security policy https://github.com/notaryproject/.github/pull/5

**Comment by yizha1** [comment]
Closed issue as https://github.com/notaryproject/.github/pull/5 merged
